### ISSUE TITLE
Figure out what to do about the RCON host address.

### ISSUE THREAD

**Issue by Michaelcraun** [mietechnologies/MIE-MCServer#33]

**Comment by Michaelcraun** [comment]
This cannot be added as an element to the server.properties file. That file is reset whenever the server boots up.

**Comment by Michaelcraun** [comment]
@BAChapin how do you feel about adding this to the `Minecraft` config section?

**Comment by Michaelcraun** [comment]
@BAChapin ?

**Comment by Michaelcraun** [comment]
@BAChapin ???

**Comment by BAChapin** [comment]
> @BAChapin how do you feel about adding this to the `Minecraft` config section?

We definitely can, if you think thats the best solution. I was hoping for something a bit more "automagical". But we can always look into more advanced solutions down the line. i.e. a library or something that could give us the external IP. Because I feel like that would be a more automatic solution, rather than having the user input it.

Not that I don't think our users wouldn't be able to figure out those details (assuming they aren't using a DDNS service), but more so to make the software more accessible and less "cumbersome". But those are my thoughts.
